#!/usr/bin/env bash
# script that displays 'To infinity and beyond' indefinitely and traps the SIGINT, SIGQUIT and SIGTERM signals
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command" && rm -f /var/run/myscript.pid && exit' SIGTERM
trap 'rm -f /var/run/myscript.pid && exit' SIGQUIT

echo $$ > /var/run/myscript.pid
i=0
while [ $i ]; do
	echo "To infinity and beyond"
	sleep 2
done;
