#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd, using the while loop + IFS
while IFS=':' read -r USERNAME PASSWD USER_ID GROUP_ID USER_INFO DIR CMD;
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $DIR and rides $CMD. $USER_ID's place is protected by the passcode $PASSWD, more info about the user here: $USER_INFO";
done < /etc/passwd
