#!/usr/bin/env bash
# script that parses apache log file using awk, ordered from the greatest to the lowest number of occurrences
# using awk alone:
# awk '{a[$1]++ } END{for (x in a) print a[x], $1" "$9 | "sort -gr"}' apache-access.log
awk '{ print $1" "$9 }' apache-access.log | sort | uniq -c | sort -gr
