#!/usr/bin/env bash
# script that parses apache log file using awk, ordered from the greatest to the lowest number of occurrences
awk '{ print $1" "$9 }' apache-access.log | sort | uniq -c | sort -gr

