#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes
i=1
j=0
while [ $j -lt 13 ]; do
	if [ $i -eq 1 ]; then
		echo "Hour: $j"
	fi;
	echo $i
	((i+=1))
	if [ $i -eq 60 ]; then
		((j+=1))
		((i=1))
	fi;
done
