#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes
i=1
j=0
while [ $j -lt 13 ]; do
	echo $i
	((i+=1))
	if [ $i -eq 59 ]; then
		((j+=1))
		if [ $j -ne 13 ]; then
			echo "Hour: $j"
		fi;
		((i=1))
	fi;
done
