#!/usr/bin/env bash
# configures an Ubuntu server to change hosts in hosts file
cp /etc/hosts ~/hosts.new
sed -i 's/^127.*$/127.0.0.2 localhost/' ~/hosts.new
sed -i 's/^157.240.11.35*$/8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
